/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigureIndexRouteImport } from './routes/configure.index'
import { Route as InterviewSlugRouteImport } from './routes/interview.$slug'
import { Route as ConfigureOrgIdRouteImport } from './routes/configure.$orgId'
import { Route as InterviewSlugCompleteRouteImport } from './routes/interview.$slug.complete'
import { Route as ConfigureOrgIdTestTestIdRouteImport } from './routes/configure.$orgId.test.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureIndexRoute = ConfigureIndexRouteImport.update({
  id: '/configure/',
  path: '/configure/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSlugRoute = InterviewSlugRouteImport.update({
  id: '/interview/$slug',
  path: '/interview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureOrgIdRoute = ConfigureOrgIdRouteImport.update({
  id: '/configure/$orgId',
  path: '/configure/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSlugCompleteRoute = InterviewSlugCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => InterviewSlugRoute,
} as any)
const ConfigureOrgIdTestTestIdRoute =
  ConfigureOrgIdTestTestIdRouteImport.update({
    id: '/test/$testId',
    path: '/test/$testId',
    getParentRoute: () => ConfigureOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configure/$orgId': typeof ConfigureOrgIdRouteWithChildren
  '/interview/$slug': typeof InterviewSlugRouteWithChildren
  '/configure/': typeof ConfigureIndexRoute
  '/interview/$slug/complete': typeof InterviewSlugCompleteRoute
  '/configure/$orgId/test/$testId': typeof ConfigureOrgIdTestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configure/$orgId': typeof ConfigureOrgIdRouteWithChildren
  '/interview/$slug': typeof InterviewSlugRouteWithChildren
  '/configure': typeof ConfigureIndexRoute
  '/interview/$slug/complete': typeof InterviewSlugCompleteRoute
  '/configure/$orgId/test/$testId': typeof ConfigureOrgIdTestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configure/$orgId': typeof ConfigureOrgIdRouteWithChildren
  '/interview/$slug': typeof InterviewSlugRouteWithChildren
  '/configure/': typeof ConfigureIndexRoute
  '/interview/$slug/complete': typeof InterviewSlugCompleteRoute
  '/configure/$orgId/test/$testId': typeof ConfigureOrgIdTestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configure/$orgId'
    | '/interview/$slug'
    | '/configure/'
    | '/interview/$slug/complete'
    | '/configure/$orgId/test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configure/$orgId'
    | '/interview/$slug'
    | '/configure'
    | '/interview/$slug/complete'
    | '/configure/$orgId/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/configure/$orgId'
    | '/interview/$slug'
    | '/configure/'
    | '/interview/$slug/complete'
    | '/configure/$orgId/test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigureOrgIdRoute: typeof ConfigureOrgIdRouteWithChildren
  InterviewSlugRoute: typeof InterviewSlugRouteWithChildren
  ConfigureIndexRoute: typeof ConfigureIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure/': {
      id: '/configure/'
      path: '/configure'
      fullPath: '/configure/'
      preLoaderRoute: typeof ConfigureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$slug': {
      id: '/interview/$slug'
      path: '/interview/$slug'
      fullPath: '/interview/$slug'
      preLoaderRoute: typeof InterviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure/$orgId': {
      id: '/configure/$orgId'
      path: '/configure/$orgId'
      fullPath: '/configure/$orgId'
      preLoaderRoute: typeof ConfigureOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$slug/complete': {
      id: '/interview/$slug/complete'
      path: '/complete'
      fullPath: '/interview/$slug/complete'
      preLoaderRoute: typeof InterviewSlugCompleteRouteImport
      parentRoute: typeof InterviewSlugRoute
    }
    '/configure/$orgId/test/$testId': {
      id: '/configure/$orgId/test/$testId'
      path: '/test/$testId'
      fullPath: '/configure/$orgId/test/$testId'
      preLoaderRoute: typeof ConfigureOrgIdTestTestIdRouteImport
      parentRoute: typeof ConfigureOrgIdRoute
    }
  }
}

interface ConfigureOrgIdRouteChildren {
  ConfigureOrgIdTestTestIdRoute: typeof ConfigureOrgIdTestTestIdRoute
}

const ConfigureOrgIdRouteChildren: ConfigureOrgIdRouteChildren = {
  ConfigureOrgIdTestTestIdRoute: ConfigureOrgIdTestTestIdRoute,
}

const ConfigureOrgIdRouteWithChildren = ConfigureOrgIdRoute._addFileChildren(
  ConfigureOrgIdRouteChildren,
)

interface InterviewSlugRouteChildren {
  InterviewSlugCompleteRoute: typeof InterviewSlugCompleteRoute
}

const InterviewSlugRouteChildren: InterviewSlugRouteChildren = {
  InterviewSlugCompleteRoute: InterviewSlugCompleteRoute,
}

const InterviewSlugRouteWithChildren = InterviewSlugRoute._addFileChildren(
  InterviewSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigureOrgIdRoute: ConfigureOrgIdRouteWithChildren,
  InterviewSlugRoute: InterviewSlugRouteWithChildren,
  ConfigureIndexRoute: ConfigureIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
